### ISSUE TITLE
Config for the nether

### ISSUE THREAD

**Issue by DrRichardEw** [Enginecrafter77/SurvivalInc#19]
Could there be a way to make it so you don't slowly lose sanity while in the nether? Because I literally cannot enter the nether for more than five minutes without my character going crazy, and no amount of dogs or sanity foods help out. I understand that you could change it so the threshold is light level 0, but that makes insanity such a moot point that its almost unnecessary.

**Comment by Enginecrafter77** [comment]
Hi. I am sorry, I didn't test the sanity in nether that thoroughly. I have looked into the issue, and it seems that it's not caused by the light level (the light effect has overworld filter applied), but rather a problem with the day-night cycle in nether. I will probably temporarily apply the same overworld filter to this effect. However, in future releases (when I pull the Sanity Overhaul update off), the classic "night = sanity drain" effect will be gone, and replaced with more advanced implementation (see [this](https://github.com/Enginecrafter77/SurvivalInc/projects/5#card-40052646) item on the Sanity Overhaul project page). I am pretty sure that the new implementation won't have such issue as you're describing.

**Comment by Enginecrafter77** [comment]
Okay, done. The only issue that persists until the update is that the nether has absolutely no impact on sanity. But I guess that's fine, at least for now.
