### ISSUE TITLE
walking on farmland decrease sanity quickly

### ISSUE THREAD

**Issue by Dararess** [Enginecrafter77/SurvivalInc#20]
walking on farmland decrease sanity quickly

**Comment by Enginecrafter77** [comment]
Hi. Thanks for reporting the issue. I will certainly look into it in. In the meanwhile, could you please elaborate the issue a little bit more? I mean, like, does it always behave like this or just sometimes? Are the light readings correct when you press F3? I know something similar to this happens when you ride a minecart through 1x2 hole, though this is pretty much unfixable and a problem of minecraft itself.

**Comment by Dararess** [comment]
the light level on block is always a 0
![2020-09-05_14 30 33](https://user-images.githubusercontent.com/69246899/92305152-b800c080-ef84-11ea-9c5e-5022a9640c97.png)

**Comment by Enginecrafter77** [comment]
Well, I will see what I can do, but the chances are not in our favor. The lighting engine seems to be flawed, and this is not the only case (for example the narrow mineshaft I mentioned).

**Comment by Enginecrafter77** [comment]
Hi. Sorry for the late update, but I think I may have fixed the issue. Put simply, the minecraft lighting code is checking the block at player's feet. In case of blocks like farmland, you are actually a bit below, so the block at player's feet is not air, but the farmland, resulting in 0 light level. I have changed it to look at the block at player's head (see 4e3a4dea777aa2018f2c7df52dd7bfcd3ccffca3). This way, you nearly always get correct result. So far I have only tested it in case of farmland and stairs/slabs. Feel free to reopen the issue if you spot any weird results yourself.
