### ISSUE TITLE
A Personal Letter

### ISSUE THREAD

**Issue by Schoperation** [Enginecrafter77/SurvivalInc#21]
Hey man, 

I just want to take some time to say thank you for continuing the project. Unfortunately I've been busy finishing my degree so I haven't had the chance to check out the mod, but I bet even before your planned overhauls that it's terrific.

And a big thanks to cleaning up all the code. High schooler me at the time barely knew the ins and outs of Java so... guess I did the best I could at the time lol. But man, looks so much better.

I've edited the project page for SchopCraft on CurseForge to add a link to your project, so people can go to the updated version.

Thanks a bunch,
-Schoperation

**Comment by Enginecrafter77** [comment]
Hey, thanks for that! I really appreciate that you took the time to contact me (even if in a rather weird way :D). I would also like to give you a huge "Thank you" for the base code this evolved from, and also for the idea. Honestly, the sole idea of Schopcraft caught my attention at first, and I thought like "Well, nearly all the other survival mods are discontinued and this looks very promising, just needs some ricing!". And... Well, this is what I ended up with :D.

Also, since I finally got the chance to get in touch with you, I would like to apologize for what the github project structure looks like. I issued a request at github staff to make this a separate project since otherwise it would not show up in my activity feed. But instead of making it fully independent, they made your repo look like a fork of this, so I am sorry for that.

Anyways, if you would like to contribute to this effort again, feel free to contact me, I am sure we could agree on something!

Best wishes to you, and again, thanks for all your awesome work on this mod's predecessor, Schopcraft!
\- Enginecrafter77
