### ISSUE TITLE
[Suggestion] Add custom effect when you are too cold or too hot

### ISSUE THREAD

**Issue by gatoborrachon** [Enginecrafter77/SurvivalInc#37]
**Is your feature request related to a problem? Please describe.**
When you are exploring the world you usually will get too hot in the desert or too cold in a snowy biome (as expected), but sometimes you only notice about this when you start receiving damage.

**Describe the solution you'd like**
Implement an effect of freezing and overheating when you are near to the limits to start getting damage.
(also, vanilla already implemented this in a 1.17 snapshot)

**Describe alternatives you've considered**
Heat and Climate adds exactly this effect when you are near a too hot or too cold temperature source, but well, it is only for its purposes, why not use the method that HaC uses but for body temp to not "reinvent the wheel"?
(look at the borders):

COLD:
![2021-05-09_14 24 51](https://user-images.githubusercontent.com/61126174/117585027-e582a880-b0d5-11eb-9fd1-55c8eb5ba6c3.png)

------------

HOT:
![2021-05-09_14 25 58](https://user-images.githubusercontent.com/61126174/117585030-e7e50280-b0d5-11eb-9284-e5b0494133ad.png)

------------

**Comment by Enginecrafter77** [comment]
I have already thought about adding such thing. The problem is that it's literally impossible to do without using shaders, and the thing is that I really such at shaders (you can see it in the sanity shader). Also, I have been really hesitant about the whole HaC thing, since I have to "decrypt" their codebase since the whole documentation is written in japanese, and my japanese levels are poor to non-existent. But I think I will have to look at it. Anyways, I just wanted to let you know that this has been one of the top priorities on my TODO list since the UI rework, so I am definitely going to work on that.

**Comment by gatoborrachon** [comment]
> Also, I have been really hesitant about the whole HaC thing, since I have to "decrypt" their codebase since the whole documentation is written in japanese,

well, the author one day told me that i can use the Google translator of Chrome to read a readme.txt about the mod (i guess it was this: https://github.com/defeatedcrow/HeatAndClimateMod/blob/1.12.2_v3/main/resources/ReadMe.txt)

but if after some research you don't want to bet your time on something that might not work, no problem, at the end i'm the only one who asked for this compat.
