### ISSUE TITLE
The GUI does not appear after updating the replacement file

### ISSUE THREAD

**Issue by ainlzj** [Enginecrafter77/SurvivalInc#45]
When I updated the replacement module and configuration file, I found that the module did not display hunger and thirst value and brain residue GUI

**Comment by ainlzj** [comment]
![W~6LV~NZF0KXQ(1H{HFM68L](https://user-images.githubusercontent.com/66135518/130326509-129c409f-2578-4de4-b83c-9b41004b848c.png)
![AHFLZH3VRH$7)IWWL AHL 3](https://user-images.githubusercontent.com/66135518/130326515-9bccbbc8-f022-4470-a5d9-d25f37c146e3.png)

**Comment by Enginecrafter77** [comment]
Sorry, but this is not enough context for me to make any conclusions. First of all, why didn't you use the provided templates? They're there to guide you and tell you what information I need in order to make any relevant conclusions. It's not that I am shaming you or anything (still a lot better than posting your issue on curseforge comments), but next time try to use the provided templates.

Second, what version are you using? What forge version are you using? What other mods (with their versions) are you running? These are very important details since some mods may be tampering with the forge rendering system, and I need to know which those are.

**Comment by ainlzj** [comment]
Thanks for reminding me that my forge is the latest version of module 2854. After my examination, I found that the disappearance of brain residual value is caused by firstaid and the disappearance of hunger and thirst value is caused by betterwithmods.

**Comment by ainlzj** [comment]
The problem has been solved. Change these two to
stackSanityBar=false 
stackHydrationBar=false

**Comment by ainlzj** [comment]
I'm really sorry to trouble you

**Comment by Enginecrafter77** [comment]
No problem.
