### ISSUE TITLE
Integration with Elenai Doge 2

### ISSUE THREAD

**Issue by hasuu** [Enginecrafter77/SurvivalInc#46]
Dodge wont work with Survival Inc. installed.
I already posted it on Elenai Doge Github.
Link to the mod: https://www.curseforge.com/minecraft/mc-mods/elenai-dodge-2

**Comment by Enginecrafter77** [comment]
> Won't work
This one. *What* doesn't work? Does the game crash? Is the game buggy? Are there glitches? Does the player keep dying? Is the inventory resetting? Is the whole world playing rickroll on an endless loop in the background? I know I'm going wild there, but "doesn't work" can literally mean million things.

So please, if it's a crash, provide the crash report. If it's a bug, provide the logs. Either way, list ALL the mods you have enabled with their versions + the version of forge. Then we can talk :)

**Comment by hasuu** [comment]
Newest forge, only your and Elenai Doge 2 installed.
When i try to doge, it just doesn't work. I press the button and nothing happens.
I already posted same issue on Elenai github.

**Comment by Enginecrafter77** [comment]
Okay... I will try to look into it. But I'm still not sure what "try to doge" means.

**Comment by hasuu** [comment]
hahahah sorry i mean dodge.  English is not my native language^^

**Comment by Enginecrafter77** [comment]
Oh okay that makes more sense. But I still need to check it on my own.

**Comment by hasuu** [comment]
I know HUD works perfect, but have you tried dodging with alt, or double tapping with WASD keys?
If you want i can make YT vid.

**Comment by Enginecrafter77** [comment]
I mean, you can... But, it would be better if you'd just write down a list of steps what you have to do and then describe what should've happened vs what really happened.

It should look something like this:
 * I press <X>
 * Then I walk forward
 * I press <Y>
 * <A> should have happened, but <B> happened instead.

**Comment by hasuu** [comment]
https://youtu.be/dNtj0vUOVDs

**Comment by Enginecrafter77** [comment]
Okay so after few hours of experimentation I have come to a conclusion that the problem lies on [this line](https://github.com/Enginecrafter77/SurvivalInc/blob/master/src/main/java/enginecrafter77/survivalinc/CommonProxy.java#L74). This line registers event handler for every kind of event, and for some reason ElenaiDodge doesn't seem to like that very much. I will see what I can do to circumvent this weird restriction.

**Comment by hasuu** [comment]
Nice and thank you for your work.

**Comment by Enginecrafter77** [comment]
Okay after some hacky work I managed to get it work. The details are provided in the javadoc and the commit message. In short, some hacky measures were implemented to generate event handler classes on demand instead of using one catch-all event handler. This should also improve performance quite a bit. I tested it with latest Elenai Dodge on 1.12.2 with default SurvivalInc config and all seemed to work well. Thus, I'm closing this.

**Comment by hasuu** [comment]
NICE! big thank you

**Comment by hasuu** [comment]
Update soon?

**Comment by Enginecrafter77** [comment]
I was planning to release it on 1st of September. But if you don't want to wait, see the [wiki page](https://github.com/Enginecrafter77/SurvivalInc/wiki/Compilation) about how to compile the bleeding edge version yourself.

**Comment by gatoborrachon** [comment]
@hasuu in case you were still waiting, there's the new release in Curseforge
