### ISSUE TITLE
Season command broken

### ISSUE THREAD

**Issue by Joshernoob** [Enginecrafter77/SurvivalInc#8]
The season manipulation command doesn't seem to respond and can sometime crash a few packs I've tested the mod in.

**Comment by Enginecrafter77** [comment]
Can you please specify which packs did the mod crash in? Or even better, could you please post the crash report (put it [here](https://pastebin.com/))? It would be a lot easier to know what has really happened.

Also, the season command does not always visibly take effect because how minecraft mechanics work. To fix this, press F3+A (reloads all chunks).

**Comment by Enginecrafter77** [comment]
Assuming the issue is abadoned by the OP.
